language: bash

services:
  - docker

before_script:
  - cp mysql/db.env.example mysql/db.env

script:
  - docker-compose -f traefik/insecure/docker-compose.yml up -d
  - docker-compose -f nginx-php-site/docker-compose.yml up -d
  - docker-compose -f mysql/docker-compose.yml up -d
  - docker ps | grep -q traefik
  - docker ps | grep -q sitename
  - docker ps | grep -q db
