version: "3.7"
services:

    sitename:
        image: justintime50/nginx-php:7.4
        restart: always
        container_name: sitename
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - traefik
        labels:
            - traefik.enabled=true
            - traefik.docker.network=traefik
            - traefik.frontend.rule=Host:sitename.localhost
            - traefik.port=80

networks:
    traefik:
        external:
            name: traefik
