version: '3.7'

services:

    db:
        image: mysql:5.7.26
        restart: always
        container_name: db
        env_file:
            - db.env
        ports:
            - '3306:3306'
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - traefik


networks:
    traefik:
        external:
            name: traefik

