version: '3.7'

services:

    db:
        image: mysql:5.7.26
        restart: always
        container_name: db
        env_file:
            - db.env
        ports:
            - '3306:3306'
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - traefik_default


networks:
    traefik_default:
        external:
            name: traefik_default

