version: '3.7'

services:

    ## Use latest Nginx to serve
    nginx1:
        image: nginx:latest
        restart: always
        container_name: 'nginx1'
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - traefik
        labels:
            - traefik.enabled=true
            - traefik.backend=nginx1
            - traefik.docker.network=traefik
            - traefik.frontend.rule=Host:nginx1.localhost
            - traefik.port=80

    ## Use latest PHP
    php1:
        image: php:fpm
        restart: always
        container_name: 'php1'
        volumes:
            - ./:/var/www
        networks:
            - traefik

networks:
    traefik:
        external:
            name: traefik