version: "3.7"
services:

    nginx2:
        image: nginx:latest
        restart: always
        container_name: nginx2
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - traefik
        labels:
            - traefik.enabled=true
            - traefik.docker.network=traefik
            - traefik.frontend.rule=Host:nginx2.localhost
            - traefik.port=80

    php2:
        image: php:fpm
        restart: always
        container_name: php2
        volumes:
            - ./:/var/www/html
        networks:
            - traefik

networks:
    traefik:
        external:
            name: traefik